#!/usr/bin/env python3
"""Generate mc_pack_converter/data/gui_scaling.json.

Modern Minecraft scales some GUI sprites with nine-slice or tiling metadata:
`widget/button.png.mcmeta` says {"gui":{"scaling":{"type":"nine_slice",
"width":200,"height":20,"border":3}}} and vanilla's button.png is exactly
200x20 — the metadata describes the texture it sits beside.

A converted pack ships those sprites at ITS resolution (400x40 at 2x, 800x80 at
4x) and, until now, no .mcmeta. Metadata is a separate resource, so Minecraft
kept vanilla's — which declares 200x20 — and applied it to a texture several
times that size. The sprite fails to resolve and renders as the missing
texture: magenta buttons, sliders, tabs and toasts on every non-1x pack.

This table records each sprite's vanilla scaling block. The converter rewrites
the pixel dimensions in it by the pack's own resolution factor.
"""
from __future__ import annotations
import json, sys, urllib.request
from pathlib import Path

OUT = Path(__file__).parent.parent / "mc_pack_converter" / "data" / "gui_scaling.json"
TREE = ("https://api.github.com/repos/InventivetalentDev/minecraft-assets"
        "/git/trees/1.21.4?recursive=1")
RAW = "https://raw.githubusercontent.com/InventivetalentDev/minecraft-assets/1.21.4/"
PREFIX = "assets/minecraft/textures/gui/sprites/"


def main() -> int:
    with urllib.request.urlopen(TREE, timeout=120) as r:
        tree = json.load(r)
    if tree.get("truncated"):
        raise SystemExit("mirror tree listing truncated; cannot generate")
    paths = sorted(p["path"] for p in tree["tree"]
                   if p["path"].startswith(PREFIX) and p["path"].endswith(".png.mcmeta"))
    out = {}
    for p in paths:
        with urllib.request.urlopen(RAW + p, timeout=60) as r:
            data = json.load(r)
        scaling = (data.get("gui") or {}).get("scaling")
        if scaling:
            out[p[len(PREFIX):-len(".png.mcmeta")]] = scaling
    OUT.write_text(json.dumps({
        "_comment": ("Vanilla's gui scaling metadata per sprite, from the 1.21.4 "
                     "mirror. GENERATED by tools/gen_gui_scaling.py; do not "
                     "hand-edit. A pack shipping one of these sprites at its own "
                     "resolution MUST ship a matching .mcmeta: metadata is a "
                     "separate resource, so without one Minecraft keeps vanilla's, "
                     "which declares vanilla's pixel dimensions, and the sprite "
                     "renders as the missing texture. Pixel fields are scaled by "
                     "the pack's resolution factor at convert time."),
        "scaling": out}, indent=1) + "\n")
    print(f"wrote scaling for {len(out)} sprites -> {OUT}")
    kinds = {}
    for v in out.values():
        kinds[v.get("type")] = kinds.get(v.get("type"), 0) + 1
    print("  types:", kinds)
    return 0


if __name__ == "__main__":
    sys.exit(main())
