#!/usr/bin/env python3
"""Generate mc_pack_converter/data/animated_textures.json.

Modern Minecraft animates exactly the textures it ships an `.mcmeta` beside.
A converted pack that overrides one of those WITHOUT an `.mcmeta` gets it drawn
as a single stretched still image — the fire bug, where a pack shipped both
filenames and the animation metadata stayed on the one that lost.

"tall and lacking an .mcmeta" is NOT the invariant: vanilla itself ships
environment/rain.png, entity/endercrystal/endercrystal_beam.png and others as
tall strips with no .mcmeta, and a naive check fired on 143 of 170 corpus packs.
The list below is the real signal, taken from the version-pinned vanilla mirror.
"""
from __future__ import annotations
import json, sys, urllib.request
from pathlib import Path

OUT = Path(__file__).parent.parent / "mc_pack_converter" / "data" / "animated_textures.json"
TREE = ("https://api.github.com/repos/InventivetalentDev/minecraft-assets"
        "/git/trees/1.21.4?recursive=1")
PREFIX = "assets/minecraft/textures/"


def main() -> int:
    with urllib.request.urlopen(TREE, timeout=120) as r:
        tree = json.load(r)
    if tree.get("truncated"):
        raise SystemExit("mirror tree listing truncated; cannot generate")
    animated = sorted(
        p["path"][len(PREFIX):-len(".png.mcmeta")]
        for p in tree["tree"]
        if p["path"].startswith(PREFIX) and p["path"].endswith(".png.mcmeta"))
    OUT.write_text(json.dumps({
        "_comment": ("Textures modern Minecraft animates, i.e. the ones vanilla "
                     "1.21.4 ships an .mcmeta beside. GENERATED by "
                     "tools/gen_animated.py; do not hand-edit. A pack overriding "
                     "one of these without its own .mcmeta draws a single "
                     "stretched still image instead of the animation. Paths are "
                     "relative to assets/minecraft/textures/, without .png."),
        "animated": animated}, indent=1) + "\n")
    print(f"wrote {len(animated)} animated texture paths -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
